"""add_name_country_to_personas

Revision ID: 8face9e20e12
Revises: 
Create Date: 2026-03-06 22:21:51.897545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8face9e20e12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('personas', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'country')
    op.drop_column('personas', 'name')
    # ### end Alembic commands ###
