export const TAXONOMY_LABELS_JA = {
  'Demographics': '基本属性',
  'Age': '年齢',
  'Gender': '性別',
  'Location': '居住地',
  'Family': '家族',
  'Nationality': '国籍・ルーツ',
  'Career and Work': '仕事・キャリア',
  'Employment': '雇用',
  'Work Style': '働き方',
  'Income': '収入',
  'Career Outlook': 'キャリア展望',
  'Workplace Relations': '職場関係',
  'Work Values': '仕事観',
  'Financial Behavior': '金銭行動',
  'Spending': '支出',
  'Saving': '貯蓄',
  'Investment': '投資',
  'Financial Literacy': '金融リテラシー',
  'Debt': '負債',
  'Insurance': '保険',
  'Money Mindset': 'お金に対する考え方',
  'Media and Information': 'メディア・情報行動',
  'News Consumption': 'ニュース接触',
  'SNS Usage': 'SNS利用',
  'Content Preferences': 'コンテンツ嗜好',
  'Ad and PR Attitude': '広告・PRへの態度',
  'Search Behavior': '検索行動',
  'Consumer Behavior': '消費行動',
  'Purchase Decision': '購買意思決定',
  'Online Shopping': 'オンライン購買',
  'Offline Shopping': 'オフライン購買',
  'Subscription Services': 'サブスク利用',
  'Brand Attitude': 'ブランド態度',
  'Values and Beliefs': '価値観・信念',
  'Core Values': '中核価値観',
  'Social Issues': '社会課題意識',
  'Political Orientation': '政治的志向',
  'Environmental Awareness': '環境意識',
  'Religion and Spirituality': '宗教・スピリチュアリティ',
  'Work Ethic': '労働倫理',
  'Worldview': '世界観',
  'Health and Wellness': '健康・ウェルネス',
  'Physical Health': '身体的健康',
  'Mental Health': 'メンタルヘルス',
  'Health Information': '健康情報',
  'Food and Drink': '食と飲み物',
  'Beauty and Grooming': '美容・身だしなみ',
  'Relationships and Social': '人間関係・社会性',
  'Social Style': '社交スタイル',
  'Communication': 'コミュニケーション',
  'Trust': '信頼',
  'Family Relations': '家族関係',
  'Romantic Relations': '恋愛・パートナー関係',
  'Community': 'コミュニティ',
  'Hobbies and Lifestyle': '趣味・ライフスタイル',
  'Indoor Activities': 'インドア活動',
  'Outdoor Activities': 'アウトドア活動',
  'Entertainment': '娯楽',
  'Fashion and Appearance': 'ファッション・外見',
  'Pets': 'ペット',
  'Travel': '旅行',
  'Education': '教育',
  'Academic Background': '学歴',
  'Continuous Learning': '継続学習',
  'Professional Certification': '資格',
  'Teaching and Mentoring': '指導・メンタリング',
  'Technology': 'テクノロジー',
  'Device Usage': 'デバイス利用',
  'Tech Savviness': 'テクノロジー習熟度',
  'AI Attitude': 'AIへの態度',
  'Privacy and Security': 'プライバシー・セキュリティ',
  'Smart Home': 'スマートホーム',
  'Social Media Tech': 'ソーシャルメディア技術理解',
  'Life Events and Context': '人生の出来事・背景',
  'Recent Changes': '最近の変化',
  'Life Satisfaction': '生活満足度',
  'Aspirations': '将来志向',
  'Regrets and Lessons': '後悔と学び',
  'Medial Specific': 'メディアル特性',
  'Article Reading Habits': '記事閲読習慣',
  'Health Information Seeking': '健康情報探索',
  'Content Engagement': 'コンテンツ関与',
  'Medial Usage Pattern': 'メディアル利用パターン',
  'Health Literacy': 'ヘルスリテラシー',
  'Specific Age': '具体的な年齢',
  'Life Stage': 'ライフステージ',
  'Generation Label': '世代ラベル',
  'Perceived Age vs Actual Age': '見た目年齢と実年齢の差',
  'Gender Identity': '性自認',
  'Pronouns': '代名詞',
  'Gender Expression Style': 'ジェンダー表現スタイル',
  'City': '市区町村',
  'Prefecture': '都道府県',
  'Urban Rural Type': '都市・地方区分',
  'Living Arrangement': '居住形態',
  'Neighborhood Character': '近隣環境の特徴',
  'Years at Current Address': '現住所の居住年数',
  'Move History': '転居歴',
  'Marital Status': '婚姻状況',
  'Children Count': '子どもの人数',
  'Children Age Range': '子どもの年齢層',
  'Household Size': '世帯人数',
  'Household Structure': '世帯構成',
  'Pet Ownership': 'ペット飼育状況',
  'Multigenerational Living': '多世代同居',
  'Cultural Background': '文化的背景',
  'Language at Home': '家庭内言語',
  'Years in Current Region': '現在地域の居住年数',
  'Regional Dialect Influence': '地域方言の影響',
  'Industry Sector': '業界',
  'Company Size': '会社規模',
  'Job Title': '職種・役職',
  'Years of Experience': '経験年数',
  'Employment Type': '雇用形態',
  'Number of Jobs Held': '経験職数',
  'Job Prestige Perception': '職業の社会的評価認識',
  'Remote Work Ratio': 'リモートワーク比率',
  'Work Hours Per Week': '週あたり労働時間',
  'Overtime Frequency': '残業頻度',
  'Work Life Balance Attitude': 'ワークライフバランス志向',
  'Commute Method': '通勤手段',
  'Commute Duration': '通勤時間',
  'Desk Setup Quality': '作業環境の充実度',
  'Meeting Load per Week': '週あたり会議量',
  'Annual Income Range': '年収帯',
  'Income Satisfaction': '収入満足度',
  'Side Job Presence': '副業の有無',
  'Side Job Type': '副業の種類',
  'Income Trajectory': '収入推移',
  'Ambition Level': '向上心の強さ',
  'Job Change Intent': '転職意向',
  'Skill Development Focus': 'スキル開発の重点',
  'Career Goal Horizon': 'キャリア目標の時間軸',
  'Management Aspiration': '管理職志向',
  'Retirement Age Goal': '希望退職年齢',
  'Team Size': 'チーム規模',
  'Manager Relationship Quality': '上司との関係性',
  'Peer Collaboration Style': '同僚との協働スタイル',
  'Meeting Frequency': '会議頻度',
  'Workplace Culture Fit': '職場文化との適合度',
  'Union Membership': '労働組合加入状況',
  'Salary vs Fulfillment Priority': '給与とやりがいの優先度',
  'Job Security Importance': '雇用安定性の重要度',
  'Company Brand Importance': '企業ブランド重視度',
  'Social Impact of Work Importance': '仕事の社会的意義の重視度',
  'Flexibility Importance': '柔軟性の重視度',
  'Autonomy vs Structure Preference': '自律性と制度の好み',
  'Recognition Need at Work': '職場での承認欲求',
  'Colleague Diversity Importance': '同僚の多様性重視度',
  'Monthly Spending Style': '月間支出スタイル',
  'Major Expense Categories': '主な支出カテゴリ',
  'Impulse Buying Tendency': '衝動買い傾向',
  'Luxury Spending Frequency': 'ぜいたく支出の頻度',
  'Discount Sensitivity': '割引への敏感さ',
  'Cash vs Card Preference': '現金とカードの好み',
  'Budgeting App Usage': '家計簿アプリ利用',
  'Monthly Savings Rate': '月間貯蓄率',
  'Savings Goals': '貯蓄目標',
  'Emergency Fund Status': '緊急資金の状況',
  'Savings Account Type': '貯蓄口座の種類',
  'Automatic Savings Setup': '自動積立設定',
  'Investment Experience Level': '投資経験レベル',
  'Risk Tolerance': 'リスク許容度',
  'Investment Products Used': '利用投資商品',
  'Monthly Investment Amount': '月間投資額',
  'Investment Information Sources': '投資情報源',
  'Crypto Interest': '暗号資産への関心',
  'Real Estate Investment Interest': '不動産投資への関心',
  'Self Assessed Knowledge Level': '自己評価の知識レベル',
  'Financial Planning Habit': '資金計画の習慣',
  'Tax Filing Approach': '税申告の進め方',
  'Financial Advisor Usage': 'ファイナンシャルアドバイザー利用',
  'Loan Types': '借入の種類',
  'Outstanding Debt Level': '未返済債務の水準',
  'Debt Attitude': '借金に対する考え方',
  'Credit Card Usage Style': 'クレジットカード利用スタイル',
  'Mortgage Status': '住宅ローン状況',
  'Insurance Types Held': '加入保険の種類',
  'Insurance Review Frequency': '保険見直し頻度',
  'Insurance Switching History': '保険乗り換え履歴',
  'Scarcity vs Abundance Mindset': '欠乏志向と豊かさ志向',
  'Money and Happiness Correlation Belief': 'お金と幸福の相関認識',
  'Financial Anxiety Level': '金銭的不安の強さ',
  'Generosity vs Frugality Balance': '気前の良さと倹約のバランス',
  'Financial Goal Clarity': '金銭目標の明確さ',
  'Attitude Toward Inheritance': '相続に対する考え方',
  'Primary News Source': '主要ニュース情報源',
  'Secondary News Source': '補助的ニュース情報源',
  'News Categories of Interest': '関心のあるニュース分野',
  'Trust in Mainstream Media': '主要メディアへの信頼度',
  'News Check Frequency per Day': '1日のニュース確認頻度',
  'Breaking News Response Speed': '速報への反応速度',
  'Fact Checking Habit': 'ファクトチェック習慣',
  'Primary Platforms': '主な利用プラットフォーム',
  'Secondary Platforms': '補助的利用プラットフォーム',
  'Daily Time Spent on SNS': '1日のSNS利用時間',
  'Posting Frequency': '投稿頻度',
  'Content Type Posted': '投稿コンテンツの種類',
  'Story vs Feed Preference': 'ストーリーズとフィードの好み',
  'Follower Count Range': 'フォロワー数帯',
  'DM Usage Frequency': 'DM利用頻度',
  'Hashtag Usage': 'ハッシュタグ利用',
  'Preferred Article Length': '好みの記事の長さ',
  'Visual vs Text Preference': '画像とテキストの好み',
  'Video Consumption Hours per Day': '1日の動画視聴時間',
  'Podcast Listening Frequency': 'ポッドキャスト視聴頻度',
  'Newsletter Subscription Count': '購読ニュースレター数',
  'Infographic Preference': 'インフォグラフィック嗜好',
  'Long Form Journalism Interest': '長文記事への関心',
  'Ad Tolerance Level': '広告許容度',
  'Trust in Sponsored Content': 'スポンサード内容への信頼度',
  'Influencer Marketing Attitude': 'インフルエンサーマーケへの態度',
  'Ad Blocker Usage': '広告ブロッカー利用',
  'PR Article Recognition Ability': 'PR記事の識別力',
  'Native Advertising Awareness': 'ネイティブ広告の認知',
  'Sponsored Post Skip Speed': 'スポンサード投稿の読み飛ばし速度',
  'Search Engine Used': '利用検索エンジン',
  'Search Frequency per Day': '1日の検索頻度',
  'Query Depth': '検索クエリの深さ',
  'Trust in Search Results': '検索結果への信頼度',
  'Voice Search Usage': '音声検索利用',
  'Image Search Usage': '画像検索利用',
  'Research Depth Before Purchase': '購入前の調査深度',
  'Review Reliance': 'レビュー依存度',
  'Brand Loyalty Level': 'ブランド忠誠度',
  'Word of Mouth Influence': '口コミの影響度',
  'Expert Opinion Reliance': '専門家意見への依存度',
  'Trial Before Buy Tendency': '試してから買う傾向',
  'Return Frequency': '返品頻度',
  'Monthly Online Shopping Frequency': '月間オンライン購買頻度',
  'Preferred Platforms': '好みのプラットフォーム',
  'Price Sensitivity': '価格感度',
  'Free Shipping Importance': '送料無料の重要度',
  'Same Day Delivery Value': '当日配送の価値認識',
  'Wishlist Usage': 'ほしい物リスト利用',
  'Subscribe and Save Interest': '定期便への関心',
  'Supermarket Visit Frequency': 'スーパー来店頻度',
  'Department Store Attitude': '百貨店への態度',
  'Convenience Store Reliance': 'コンビニ依存度',
  'Specialty Store Preference': '専門店志向',
  'Browsing for Fun Tendency': '目的なく見て回る傾向',
  'Current Subscriptions List': '現在利用中のサブスク',
  'Monthly Subscription Budget': '月間サブスク予算',
  'Willingness to Pay for Content': 'コンテンツ課金意欲',
  'Subscription Cancellation Pattern': 'サブスク解約パターン',
  'Free Trial Conversion Rate': '無料体験からの継続率',
  'Domestic vs Foreign Brand Preference': '国内ブランドと海外ブランドの好み',
  'Emerging Brand Openness': '新興ブランド受容性',
  'Luxury Brand Interest': '高級ブランドへの関心',
  'Sustainable Brand Premium Willingness': 'サステナブルブランドへの上乗せ許容',
  'Brand Storytelling Resonance': 'ブランドストーリーへの共感度',
  'Top Personal Value 1': '最重要の個人価値観1',
  'Top Personal Value 2': '最重要の個人価値観2',
  'Top Personal Value 3': '最重要の個人価値観3',
  'Life Philosophy Statement': '人生哲学',
  'Core Value Consistency in Behavior': '行動における価値観の一貫性',
  'Social Issue Interest Level': '社会課題への関心度',
  'Specific Causes Supported': '支持する具体的な社会課題',
  'Donation Frequency': '寄付頻度',
  'Activism Level': 'アクティビズムの度合い',
  'Volunteer Activity Frequency': 'ボランティア頻度',
  'General Political Stance': '全体的な政治スタンス',
  'Voting Behavior': '投票行動',
  'Policy Priority Area': '重視する政策分野',
  'Political Discussion Comfort Level': '政治談議への抵抗感',
  'Environmental Concern Level': '環境問題への関心度',
  'Eco Friendly Behavior Count': '環境配慮行動数',
  'Carbon Footprint Awareness': 'カーボンフットプリント認知',
  'Sustainable Product Preference': '持続可能な商品の選好',
  'Public Transport Usage for Environment': '環境配慮での公共交通利用',
  'Religious Affiliation': '宗教的帰属',
  'Spirituality Importance': 'スピリチュアリティの重要度',
  'Practice Frequency': '実践頻度',
  'Superstition Level': '迷信傾向',
  'Effort vs Outcome Balance': '努力と成果の捉え方',
  'Attitude Toward Overwork': '長時間労働への態度',
  'Meritocracy Belief': '実力主義への信念',
  'Grit and Perseverance Self Rating': 'やり抜く力の自己評価',
  'Optimism vs Pessimism Scale': '楽観性と悲観性の尺度',
  'Individualism vs Collectivism Lean': '個人主義と集団主義の傾向',
  'Tradition vs Progress Preference': '伝統と進歩の好み',
  'Global vs Local Mindset': 'グローバル志向とローカル志向',
  'Fate vs Agency Belief': '運命と自己決定の捉え方',
  'Attitude Toward Uncertainty': '不確実性への態度',
  'Exercise Frequency per Week': '週あたり運動頻度',
  'Exercise Type': '運動の種類',
  'Diet Style': '食生活スタイル',
  'Health Concern Level': '健康への関心度',
  'Body Satisfaction': '身体満足度',
  'Sleep Hours per Night': '1日の睡眠時間',
  'Chronic Condition Presence': '慢性疾患の有無',
  'Current Stress Level': '現在のストレス水準',
  'Coping Mechanisms': 'ストレス対処法',
  'Therapy or Counseling Usage': 'カウンセリング利用',
  'Burnout History': '燃え尽き経験',
  'Happiness Self Rating': '幸福度の自己評価',
  'Anxiety Level': '不安の強さ',
  'Mindfulness Practice': 'マインドフルネス実践',
  'Trust in Health Content Online': 'オンライン健康情報への信頼度',
  'Supplement Usage': 'サプリメント利用',
  'Health App Usage': '健康アプリ利用',
  'Doctor Visit Frequency': '受診頻度',
  'Preventive Health Attitude': '予防医療への姿勢',
  'Self Diagnosis Tendency': '自己診断傾向',
  'Cuisine Preferences': '好みの料理ジャンル',
  'Dietary Restriction': '食事制限',
  'Dining Out Frequency per Month': '月間外食頻度',
  'Cooking Frequency per Week': '週あたり自炊頻度',
  'Cooking Skill Level': '料理スキル',
  'Alcohol Consumption Frequency': '飲酒頻度',
  'Coffee Tea Preference': 'コーヒーとお茶の好み',
  'Delivery Service Usage': 'デリバリーサービス利用',
  'Skincare Routine Complexity': 'スキンケア工程の複雑さ',
  'Makeup Usage': 'メイク利用',
  'Hair Care Investment': 'ヘアケアへの投資',
  'Beauty Budget Monthly': '月間美容予算',
  'Salon Visit Frequency': 'サロン来店頻度',
  'Natural vs Synthetic Product Preference': '天然由来と合成製品の好み',
  'Anti Aging Product Interest': 'エイジングケア商品の関心',
  'Fragrance Usage': '香水利用',
  'Introvert Extrovert Scale': '内向性と外向性の尺度',
  'Friend Circle Size': '友人関係の広さ',
  'Social Gathering Frequency': '社交の場への参加頻度',
  'Preferred Social Setting': '好みの交流場面',
  'Online vs Offline Social Preference': 'オンラインと対面交流の好み',
  'Preferred Communication Tools': '好みの連絡手段',
  'Response Speed Expectation': '返信速度への期待',
  'Emoji and Sticker Usage': '絵文字・スタンプ利用',
  'Phone Call Comfort Level': '電話への抵抗感',
  'Video Call Comfort Level': 'ビデオ通話への抵抗感',
  'Trust in Strangers Scale': '他者一般への信頼度',
  'Trust in Government': '政府への信頼度',
  'Trust in Corporations': '企業への信頼度',
  'Trust in Online Reviews': 'オンラインレビューへの信頼度',
  'Trust in AI': 'AIへの信頼度',
  'Trust in Science': '科学への信頼度',
  'Family Contact Frequency': '家族との連絡頻度',
  'Family Obligation Attitude': '家族責任への考え方',
  'Parenting Style if Applicable': '子育てスタイル',
  'Elder Care Involvement': '介護への関与',
  'Relationship Status': '交際状況',
  'Relationship Duration': '交際期間',
  'Partner Value Alignment': 'パートナーとの価値観一致度',
  'Work Life Balance in Relationship': '関係における仕事と生活のバランス',
  'Local Community Involvement': '地域コミュニティへの関与',
  'Neighborhood Relations': '近隣住民との関係',
  'Online Community Participation': 'オンラインコミュニティ参加',
  'Alumni Network Activity': '同窓ネットワーク活動',
  'Industry Association Membership': '業界団体加入状況',
  'Civic Engagement Level': '市民活動への関与度',
  'Reading Frequency': '読書頻度',
  'Book Genre Preference': '好みの書籍ジャンル',
  'Gaming Frequency': 'ゲーム頻度',
  'Game Genre Preference': '好みのゲームジャンル',
  'Creative Hobbies': '創作系の趣味',
  'DIY Attitude': 'DIYへの姿勢',
  'Puzzle and Board Game Interest': 'パズル・ボードゲームへの関心',
  'Sports Participation Type': 'スポーツ参加形態',
  'Travel Frequency per Year': '年間旅行頻度',
  'Travel Style': '旅行スタイル',
  'Nature Activity Preference': '自然活動の好み',
  'Urban Exploration Habit': '街歩き習慣',
  'Music Genre Preference': '好みの音楽ジャンル',
  'Live Concert Attendance': 'ライブ参加頻度',
  'Movie Drama Preference': '映画・ドラマの好み',
  'Anime Manga Attitude': 'アニメ・マンガへの態度',
  'Theater Arts Interest': '舞台芸術への関心',
  'Comedy vs Drama Preference': 'コメディとドラマの好み',
  'Fashion Consciousness': 'ファッション意識',
  'Clothing Budget Monthly': '月間被服費',
  'Brand Awareness in Fashion': 'ファッションブランド認知',
  'Grooming Routine Complexity': '身だしなみ習慣の複雑さ',
  'Secondhand Clothing Interest': '古着への関心',
  'Pet Type': '飼育ペットの種類',
  'Pet Spending Monthly': '月間ペット支出',
  'Pet Social Media Activity': 'ペット関連SNS活動',
  'Domestic vs International Travel Ratio': '国内旅行と海外旅行の比率',
  'Accommodation Preference': '宿泊先の好み',
  'Travel Companion Preference': '旅行相手の好み',
  'Travel Planning Style': '旅行計画スタイル',
  'Budget per Trip': '1回の旅行予算',
  'Souvenir Buying Habit': 'お土産購入習慣',
  'Travel Photography Habit': '旅行写真の撮影習慣',
  'Food Tourism Interest': '食目的の旅行への関心',
  'Cultural Experience Priority': '文化体験の優先度',
  'Adventure vs Relaxation Balance': '冒険と癒やしのバランス',
  'Travel Frequency Regret': '旅行頻度への後悔',
  'Highest Education Level': '最終学歴',
  'Field of Study': '専攻分野',
  'University Type': '学校種別',
  'Academic Achievement Self Assessment': '学業成績の自己評価',
  'School Club Involvement': '部活動・サークル参加',
  'Learning Style Preference': '好みの学習スタイル',
  'Current Learning Topics': '現在学んでいる内容',
  'Online Course Usage': 'オンライン講座利用',
  'Books Read per Year': '年間読書冊数',
  'Language Learning Status': '語学学習状況',
  'Certification Pursuit': '資格取得への取り組み',
  'Certifications Held': '保有資格',
  'Certification Relevance to Current Job': '現職との資格関連性',
  'Continuing Education Budget': '継続教育予算',
  'Mentorship Role': 'メンター役割',
  'Knowledge Sharing Habit': '知識共有の習慣',
  'Teaching Others Comfort Level': '他者に教えることへの抵抗感',
  'Peer Learning Participation': '仲間との学習参加',
  'Study Group Experience': '勉強会経験',
  'Primary Device Type': '主に使うデバイス',
  'OS Preference': 'OSの好み',
  'Daily Screen Time Hours': '1日の画面利用時間',
  'Device Upgrade Frequency': 'デバイス買い替え頻度',
  'Number of Devices Owned': '所有デバイス数',
  'Self Assessed Tech Skill Level': '自己評価のITスキル',
  'New Technology Adoption Speed': '新技術の導入速度',
  'Tech Support Role in Social Circle': '周囲でのITサポート役',
  'Beta Testing Participation': 'ベータテスト参加',
  'Current AI Tools Used': '現在利用中のAIツール',
  'AI Trust Level': 'AI信頼度',
  'AI Concern Areas': 'AIに関する懸念領域',
  'AI in Work Adoption': '仕事でのAI活用',
  'AI Creativity Tool Usage': '生成AIクリエイティブツール利用',
  'Chatbot Comfort Level': 'チャットボットへの抵抗感',
  'Privacy Awareness Level': 'プライバシー意識',
  'VPN Usage': 'VPN利用',
  'Password Management Approach': 'パスワード管理方法',
  'Data Sharing Comfort Level': 'データ共有への抵抗感',
  'Cookie Consent Behavior': 'Cookie同意行動',
  'Smart Device Count': 'スマートデバイス数',
  'IoT Adoption Attitude': 'IoT導入への態度',
  'Smart Speaker Usage': 'スマートスピーカー利用',
  'Algorithm Awareness': 'アルゴリズム認知',
  'Platform Algorithm Trust': 'プラットフォームアルゴリズムへの信頼',
  'Filter Bubble Awareness': 'フィルターバブル認知',
  'Digital Detox Frequency': 'デジタルデトックス頻度',
  'Screen Time Concern Level': 'スクリーンタイムへの懸念度',
  'Notification Management Style': '通知管理スタイル',
  'App Permission Scrutiny': 'アプリ権限確認の厳しさ',
  'Major Life Events Last Two Years': '直近2年の大きなライフイベント',
  'Current Life Challenge': '現在の人生課題',
  'Near Term Life Plan': '直近のライフプラン',
  'Upcoming Milestone': '今後の節目',
  'Overall Life Satisfaction Score': '総合生活満足度',
  'Primary Area for Improvement': '最優先の改善領域',
  'Sense of Purpose Level': '生きがいの実感度',
  'Work Satisfaction vs Life Satisfaction Balance': '仕事満足度と生活満足度のバランス',
  'Dream Lifestyle Description': '理想の暮らしのイメージ',
  'Five Year Vision': '5年後のビジョン',
  'Legacy Concern Level': '何を残すかへの意識',
  'Bucket List Item': '人生でやりたいこと',
  'Biggest Past Regret Area': '最も大きい過去の後悔分野',
  'Key Life Lesson': '人生で得た重要な学び',
  'Growth Mindset Level': '成長志向の強さ',
  'Resilience After Failure': '失敗後の立ち直り力',
  'Risk Taking History': 'リスクを取った経験',
  'Comfort Zone Expansion Willingness': 'コンフォートゾーン拡張意欲',
  'Daily Reading Time Minutes': '1日の読書時間（分）',
  'Preferred Article Topics': '好みの記事テーマ',
  'Article Discovery Method': '記事の発見方法',
  'Reading Device': '記事閲読デバイス',
  'Completion Rate of Long Articles': '長文記事の読了率',
  'Skimming vs Deep Reading Style': '流し読みと熟読の傾向',
  'Medical Article Reading Frequency': '医療記事の閲読頻度',
  'Trust in Medical Journalism': '医療報道への信頼度',
  'Self Diagnosis Tendency via Articles': '記事経由の自己診断傾向',
  'Doctor Advice vs Online Advice Balance': '医師助言とオンライン情報の重み付け',
  'Health App Trust Level': '健康アプリへの信頼度',
  'Like and Reaction Frequency': 'いいね・リアクション頻度',
  'Comment Posting Frequency': 'コメント投稿頻度',
  'Article Sharing Frequency': '記事共有頻度',
  'Save for Later Habit': 'あとで読む保存習慣',
  'Quote Sharing Behavior': '引用共有行動',
  'Feature Discovery Style': '機能発見スタイル',
  'Push Notification Attitude': 'プッシュ通知への態度',
  'App Check Frequency per Day': '1日のアプリ確認頻度',
  'Personalization Feature Openness': 'パーソナライズ機能への受容性',
  'Dark Mode Preference': 'ダークモードの好み',
  'Reading List Usage': 'リーディングリスト利用',
  'Medical Terminology Comfort': '医療用語への抵抗感',
  'Research Paper Reading Ability': '論文読解力',
  'Evidence Based Thinking Level': 'エビデンス重視の度合い',
  'Alternative Medicine Openness': '代替医療への受容性',
  'Second Opinion Seeking Habit': 'セカンドオピニオン習慣',
  'Clinical Trial Awareness': '臨床試験への認知',
  'Peer Health Discussion Frequency': '健康話題を周囲と話す頻度',
  'Medical History Tracking Habit': '健康履歴の記録習慣',
};

export function translateTaxonomyLabel(label) {
  if (!label) return label;
  return TAXONOMY_LABELS_JA[label] || label;
}
